# Copyright 2014-2016 Spotify AB
# Copyright 2016-2019 The Last Pickle Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Build and Test

on:
  push:
    paths-ignore:
      - "untagged-.**"
      - "master-snapshot.**"
#  pull_request:
#    paths-ignore:
#      - "untagged-.**"
#      - "master-snapshot.**"

env:
  LOCAL_JMX: no
  TEST: ""
  TEST_TYPE: ""

jobs:
  tests-with-ccm:
    env:
      TEST_TYPE: "ccm"
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.5
        uses: actions/setup-python@v1
        with:
          python-version: 3.5
      - name: Setup Java Action
        uses: actions/setup-java@v1
        with:
          java-version: '1.8'
          architecture: x64
      - name: Setup Python venv
        run: |
          python3 -m venv venv
          source venv/bin/activate
      - name: Before Install
        run: |
          source venv/bin/activate
          wget http://launchpadlibrarian.net/109052632/python-support_1.0.15_all.deb
          sudo dpkg -i python-support_1.0.15_all.deb
          ./src/ci/before_install.sh
      - name: Install
        run: |
          source venv/bin/activate
          ./src/ci/install.sh
      - name: Before Script
        run: |
            source venv/bin/activate
            ./src/ci/before_script.sh
